# Generated by Django 2.2.4 on 2019-09-09 15:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('state', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'active'), (2, 'pending activation'), (3, 'locked'), (4, 'removed')], null=True)),
                ('kind', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'bussines'), (2, 'client'), (3, 'administrator')], null=True)),
                ('score', models.PositiveSmallIntegerField(null=True)),
                ('imageAvatar', models.ImageField(blank=True, null=True, upload_to='avatar_image')),
                ('imageFront', models.ImageField(blank=True, null=True, upload_to='front_image')),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Empleoyees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('imageEmployee', models.ImageField(blank=True, null=True, upload_to='Employees')),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleoyees',
                'verbose_name_plural': 'Empleoyees',
            },
        ),
        migrations.CreateModel(
            name='WorkItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHoursEmpleoyess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_date', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('finish_date', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('init_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('empleoyee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautycalendar.Empleoyees')),
            ],
        ),
        migrations.CreateModel(
            name='UserDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('empleoyee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautycalendar.Empleoyees')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField()),
                ('imagePublication', models.ImageField(upload_to='Publications')),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'producto'), (2, 'servicio')])),
                ('title', models.CharField(max_length=50)),
                ('imageProduct', models.ImageField(blank=True, null=True, upload_to='Products')),
                ('price', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content users',
                'verbose_name_plural': 'Content users',
            },
        ),
        migrations.CreateModel(
            name='CommentsPublications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautycalendar.Publications')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BeautySalons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautycalendar.WorkItems')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikesPublications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautycalendar.Publications')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('publication', 'user')},
            },
        ),
    ]
