# Generated by Django 2.2.4 on 2019-09-06 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('state', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'active'), (2, 'pending activation'), (3, 'locked'), (4, 'removed')], null=True)),
                ('kind', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'bussines'), (2, 'client'), (3, 'administrator')], null=True)),
                ('score', models.PositiveSmallIntegerField(null=True)),
                ('imageAvatar', models.ImageField(blank=True, null=True, upload_to='avatar_image')),
                ('imageFront', models.ImageField(blank=True, null=True, upload_to='front_image')),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'producto'), (2, 'servicio')])),
                ('title', models.CharField(max_length=50)),
                ('imageProduct', models.ImageField(blank=True, null=True, upload_to='Products')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
