# Generated by Django 2.2.4 on 2019-09-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='reputacion',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
