# Generated by Django 2.2.4 on 2019-09-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleoyees',
            old_name='imageEmployee',
            new_name='imageEmpleoyee',
        ),
    ]
