# Generated by Django 2.2.4 on 2019-08-23 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_usuario',
            name='descripcion',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
