# Generated by Django 2.2.4 on 2019-08-25 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0002_tipo_usuario_descripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo_Usuario',
            new_name='EstadosUsuario',
        ),
        migrations.RenameModel(
            old_name='Estado_Usuario',
            new_name='TiposUsuario',
        ),
        migrations.RenameField(
            model_name='estadosusuario',
            old_name='id_Tipo_Usuario',
            new_name='idEstadoUsuario',
        ),
        migrations.RenameField(
            model_name='tiposusuario',
            old_name='id_Estado_Usuario',
            new_name='idTipoUsuario',
        ),
    ]
