# Generated by Django 2.2.4 on 2019-09-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0002_auto_20190902_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='imagen',
            new_name='imagenAvatar',
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagenPortada',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
