# Generated by Django 2.2.4 on 2019-09-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0002_auto_20190909_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beautysalons',
            options={'verbose_name': 'Salons', 'verbose_name_plural': 'Salons'},
        ),
        migrations.AlterModelOptions(
            name='workitems',
            options={'verbose_name': 'Work items', 'verbose_name_plural': 'Work items'},
        ),
    ]
