# Generated by Django 2.2.4 on 2019-09-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0004_auto_20190903_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'activo'), (2, 'pendiente de activacion'), (3, 'bloqueado'), (4, 'eliminado')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'bussines'), (2, 'cliente'), (3, 'administrador')]),
        ),
        migrations.DeleteModel(
            name='EstadosUsuario',
        ),
        migrations.DeleteModel(
            name='TiposUsuario',
        ),
    ]
