# Generated by Django 2.2.4 on 2019-09-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0004_publications_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentspublications',
            name='comment',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentusers',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'active'), (2, 'paused'), (4, 'removed')], null=True),
        ),
        migrations.AlterField(
            model_name='contentusers',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'product'), (2, 'service')]),
        ),
        migrations.AlterField(
            model_name='publications',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'active'), (2, 'locked'), (4, 'removed')], null=True),
        ),
    ]
