# Generated by Django 2.2.4 on 2019-09-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0005_auto_20190917_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleoyees',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'active'), (2, 'paused'), (3, 'removed')], null=True),
        ),
        migrations.AlterField(
            model_name='contentusers',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'active'), (2, 'paused'), (3, 'removed')], null=True),
        ),
    ]
