# Generated by Django 2.2.4 on 2019-09-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0008_beautysalons_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beautysalons',
            name='name',
        ),
        migrations.AddField(
            model_name='users',
            name='name_salon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
