# Generated by Django 2.2.4 on 2019-09-26 13:02

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0009_auto_20190925_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='imageAvatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[200, 200], upload_to='avatar_image'),
        ),
    ]
