# Generated by Django 2.2.4 on 2019-09-26 13:24

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0010_auto_20190926_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='imageAvatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=90, size=[150, 150], upload_to='avatar_image'),
        ),
    ]
