# Generated by Django 2.2.4 on 2019-10-01 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0013_auto_20190926_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghoursempleoyess',
            name='finish_date',
            field=models.PositiveSmallIntegerField(choices=[(1, 'domingo'), (2, 'lunes'), (3, 'martes'), (4, 'miercoles'), (5, 'jueves'), (6, 'viernes'), (7, 'sabado')], validators=[django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='workinghoursempleoyess',
            name='init_date',
            field=models.PositiveSmallIntegerField(choices=[(1, 'domingo'), (2, 'lunes'), (3, 'martes'), (4, 'miercoles'), (5, 'jueves'), (6, 'viernes'), (7, 'sabado')], validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
