# Generated by Django 2.2.4 on 2019-10-01 21:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0014_auto_20191001_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHoursSalons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_date', models.PositiveSmallIntegerField(choices=[(1, 'domingo'), (2, 'lunes'), (3, 'martes'), (4, 'miercoles'), (5, 'jueves'), (6, 'viernes'), (7, 'sabado')], validators=[django.core.validators.MaxValueValidator(6)])),
                ('finish_date', models.PositiveSmallIntegerField(choices=[(1, 'domingo'), (2, 'lunes'), (3, 'martes'), (4, 'miercoles'), (5, 'jueves'), (6, 'viernes'), (7, 'sabado')], validators=[django.core.validators.MaxValueValidator(6)])),
                ('init_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='WorkingHoursEmpleoyess',
        ),
    ]
