# Generated by Django 2.2.4 on 2019-10-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0015_auto_20191001_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentusers',
            name='attencion_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
