# Generated by Django 2.2.4 on 2019-10-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0016_contentusers_attencion_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghourssalons',
            options={'verbose_name': 'Working hours salons', 'verbose_name_plural': 'Workin hours salons'},
        ),
    ]
