# Generated by Django 2.2.4 on 2019-10-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0017_auto_20191006_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentusers',
            old_name='attencion_time',
            new_name='attention_time',
        ),
        migrations.RenameField(
            model_name='userdates',
            old_name='user',
            new_name='client',
        ),
        migrations.AddField(
            model_name='userdates',
            name='salon',
            field=models.CharField(default='00:00', max_length=50),
            preserve_default=False,
        ),
    ]
