# Generated by Django 2.2.4 on 2019-10-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0018_auto_20191007_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdates',
            name='finish_time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdates',
            name='init_time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
