# Generated by Django 2.2.4 on 2019-10-07 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0019_auto_20191007_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdates',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautycalendar.ContentUsers'),
        ),
    ]
