# Generated by Django 2.2.4 on 2019-10-09 18:23

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0023_auto_20191007_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentusers',
            name='attention_time',
        ),
        migrations.RemoveField(
            model_name='userdates',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='userdates',
            name='init_time',
        ),
        migrations.RemoveField(
            model_name='workinghourssalons',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='workinghourssalons',
            name='init_time',
        ),
        migrations.AlterField(
            model_name='publications',
            name='imagePublication',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=90, size=[300, 300], upload_to='Publications'),
        ),
    ]
