# Generated by Django 2.2.4 on 2019-10-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0023_auto_20191007_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentusers',
            name='attention_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdates',
            name='finish_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdates',
            name='init_time',
            field=models.IntegerField(),
        ),
    ]
