# Generated by Django 2.2.4 on 2019-10-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0024_auto_20191009_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdates',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='userdates',
            name='init_time',
        ),
        migrations.RemoveField(
            model_name='workinghourssalons',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='workinghourssalons',
            name='init_time',
        ),
    ]
