# Generated by Django 2.2.4 on 2019-10-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0024_auto_20191009_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentusers',
            name='attention_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdates',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdates',
            name='init_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workinghourssalons',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workinghourssalons',
            name='init_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
