# Generated by Django 2.2.4 on 2019-10-07 19:03

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0024_auto_20191007_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='imagePublication',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=90, size=[300, 300], upload_to='Publications'),
        ),
    ]
