# Generated by Django 2.2.4 on 2019-10-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0025_auto_20191007_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentusers',
            name='attention_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdates',
            name='finish_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userdates',
            name='init_time',
            field=models.DateTimeField(),
        ),
    ]
