# Generated by Django 2.2.4 on 2019-10-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0025_auto_20191009_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informer', models.IntegerField()),
                ('informed', models.IntegerField()),
                ('options', models.PositiveSmallIntegerField(choices=[(1, 'Mal servicio'), (2, 'Precios desactualizados'), (3, 'No cumple con los turnos'), (4, 'Otro')])),
                ('other', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
