# Generated by Django 2.2.4 on 2019-10-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0026_auto_20191009_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentusers',
            name='attention_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workinghourssalons',
            name='finish_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workinghourssalons',
            name='init_time',
            field=models.DateField(),
        ),
    ]
