# Generated by Django 2.2.4 on 2019-10-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0027_auto_20191009_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghourssalons',
            name='finish_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='workinghourssalons',
            name='init_time',
            field=models.TimeField(),
        ),
    ]
