# Generated by Django 2.2.4 on 2019-10-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0028_auto_20191009_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghourssalons',
            name='finish_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workinghourssalons',
            name='init_time',
            field=models.DateTimeField(),
        ),
    ]
