# Generated by Django 2.2.4 on 2019-10-20 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0028_likespublications_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draws',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('finish_day', models.DateTimeField()),
                ('state', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'actived'), (2, 'finalized')], null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Draws',
                'verbose_name_plural': 'Draws',
            },
        ),
        migrations.AlterModelOptions(
            name='reports',
            options={'verbose_name': 'Reports', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterModelOptions(
            name='userdates',
            options={'verbose_name': 'Dates', 'verbose_name_plural': 'Dates'},
        ),
        migrations.CreateModel(
            name='DrawsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautycalendar.Draws')),
            ],
            options={
                'verbose_name': 'Lists draws',
                'verbose_name_plural': 'Lists draws',
                'unique_together': {('draw', 'client')},
            },
        ),
    ]
