# Generated by Django 2.2.4 on 2019-10-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0029_auto_20191020_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='draws',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
