# Generated by Django 2.2.4 on 2019-10-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0030_draws_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draws',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
