# Generated by Django 2.2.4 on 2019-11-04 12:27

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('beautycalendar', '0031_auto_20191021_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentusers',
            name='imageProduct',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, size=[100, 100], upload_to='Products'),
        ),
        migrations.AlterField(
            model_name='empleoyees',
            name='imageEmpleoyee',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, size=[100, 100], upload_to='Employees'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='imagePublication',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, size=[300, 300], upload_to='Publications'),
        ),
        migrations.AlterField(
            model_name='users',
            name='imageAvatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, size=[150, 150], upload_to='avatar_image'),
        ),
        migrations.AlterField(
            model_name='users',
            name='imageFront',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, size=[1281, 236], upload_to='front_image'),
        ),
    ]
